// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu6HQL5zQ4ob9Olk2_s5NcZDAQshQ3cp4',
    appId: '1:832811627488:android:ca4ef953a663000a243185',
    messagingSenderId: '832811627488',
    projectId: 'clockproject-23139',
    storageBucket: 'clockproject-23139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvrFlhNGrcdhCuYw0afpzrY_Goo4vQ554',
    appId: '1:832811627488:ios:d099d948c4d53595243185',
    messagingSenderId: '832811627488',
    projectId: 'clockproject-23139',
    storageBucket: 'clockproject-23139.appspot.com',
    iosBundleId: 'com.example.menejemenWaktu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvrFlhNGrcdhCuYw0afpzrY_Goo4vQ554',
    appId: '1:832811627488:ios:d099d948c4d53595243185',
    messagingSenderId: '832811627488',
    projectId: 'clockproject-23139',
    storageBucket: 'clockproject-23139.appspot.com',
    iosBundleId: 'com.example.menejemenWaktu',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9CfYw1W2cALKbFBr2nxTKTIDQtTSo2yU',
    appId: '1:832811627488:web:195b1833ee644b42243185',
    messagingSenderId: '832811627488',
    projectId: 'clockproject-23139',
    authDomain: 'clockproject-23139.firebaseapp.com',
    storageBucket: 'clockproject-23139.appspot.com',
    measurementId: 'G-CDZSZNGE0F',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9CfYw1W2cALKbFBr2nxTKTIDQtTSo2yU',
    appId: '1:832811627488:web:841e0a8acd096b98243185',
    messagingSenderId: '832811627488',
    projectId: 'clockproject-23139',
    authDomain: 'clockproject-23139.firebaseapp.com',
    storageBucket: 'clockproject-23139.appspot.com',
    measurementId: 'G-XLXP1LP5F7',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
